{
    "type": "error",
    "data": "Error exporting table",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/exporter.py\", line 41, in export\n    await self._storage.set(filename, data.to_parquet())\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n  File \"pyarrow/array.pxi\", line 339, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 85, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: (\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')\n",
    "source": "(\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')",
    "details": null
}
{
    "type": "error",
    "data": "Error exporting table",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/exporter.py\", line 41, in export\n    await self._storage.set(filename, data.to_parquet())\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n  File \"pyarrow/array.pxi\", line 339, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 85, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: (\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')\n",
    "source": "(\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_viztree\" in create_final_viztree: create_final_viztree() missing 1 required positional argument: 'summarization_strategy'",
    "stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/workspace/graphrag/index/workflows/v1/create_final_viztree.py\", line 73, in workflow\n    output = await create_final_viztree(\nTypeError: create_final_viztree() missing 1 required positional argument: 'summarization_strategy'\n",
    "source": "create_final_viztree() missing 1 required positional argument: 'summarization_strategy'",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/run/run.py\", line 262, in run_pipeline\n    result = await _process_workflow(\n  File \"/workspace/graphrag/index/run/workflow.py\", line 107, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/workspace/graphrag/index/workflows/v1/create_final_viztree.py\", line 73, in workflow\n    output = await create_final_viztree(\nTypeError: create_final_viztree() missing 1 required positional argument: 'summarization_strategy'\n",
    "source": "create_final_viztree() missing 1 required positional argument: 'summarization_strategy'",
    "details": null
}
{
    "type": "error",
    "data": "Error exporting table",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/exporter.py\", line 41, in export\n    await self._storage.set(filename, data.to_parquet())\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n  File \"pyarrow/array.pxi\", line 339, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 85, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: (\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')\n",
    "source": "(\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')",
    "details": null
}
{
    "type": "error",
    "data": "Error exporting table",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/exporter.py\", line 41, in export\n    await self._storage.set(filename, data.to_parquet())\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n  File \"pyarrow/array.pxi\", line 339, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 85, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: (\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')\n",
    "source": "(\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_viztree\" in create_final_viztree: \"['level'] not found in axis\"",
    "stack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/workspace/graphrag/index/workflows/v1/create_final_viztree.py\", line 73, in workflow\n    output = await create_final_viztree(\n  File \"/workspace/graphrag/index/flows/create_final_viztree.py\", line 35, in create_final_viztree\n    .drop(\"level\")\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['level'] not found in axis\"\n",
    "source": "\"['level'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/run/run.py\", line 262, in run_pipeline\n    result = await _process_workflow(\n  File \"/workspace/graphrag/index/run/workflow.py\", line 107, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/workspace/graphrag/index/workflows/v1/create_final_viztree.py\", line 73, in workflow\n    output = await create_final_viztree(\n  File \"/workspace/graphrag/index/flows/create_final_viztree.py\", line 35, in create_final_viztree\n    .drop(\"level\")\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['level'] not found in axis\"\n",
    "source": "\"['level'] not found in axis\"",
    "details": null
}
{
    "type": "error",
    "data": "Error exporting table",
    "stack": "Traceback (most recent call last):\n  File \"/workspace/graphrag/index/exporter.py\", line 41, in export\n    await self._storage.set(filename, data.to_parquet())\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/usr/local/lib/python3.10/dist-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n  File \"pyarrow/array.pxi\", line 339, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 85, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: (\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')\n",
    "source": "(\"Could not convert 'b3de4456c576570c6731ea7909ad9ba69d77ef99f23f5767bff56871025fe67a78e2cb87930a28b853e42e13e6f175e40e6915e91c87002c2d04006272df136b' with type str: tried to convert to int64\", 'Conversion failed for column parent with type object')",
    "details": null
}
